services:

  llm: &llm
    image: ollama/ollama:latest
    profiles: ["linux"]
    networks:
      - net

  llm-gpu-nvidia:
    <<: *llm
    profiles: ["linux-gpu-nvidia"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    devices:
      - "/dev/nvidiactl:/dev/nvidiactl"
      - "/dev/nvidia-uvm:/dev/nvidia-uvm"
      - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
      - "/dev/nvidia-modeset:/dev/nvidia-modeset"
      - "/dev/nvidia0:/dev/nvidia0"
            
  llm-gpu-amd:
    <<: *llm
    profiles: ["linux-gpu-amd"]
    image: ollama/ollama:rocm
    environment:
      - HSA_OVERRIDE_GFX_VERSION=11.0.2
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"

  pull-model:
    image: genai-stack/pull-model:latest
    build:
      context: .
      dockerfile: pull_model.Dockerfile
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL-http://host.docker.internal:11434}
      - LLM=${LLM-llama2}
    networks:
      - net
    tty: true

  database:
    user: "${UID}:${GID}"
    image: neo4j:${NEO4J_VERSION-5.22.0}-enterprise
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - $PWD/data:/data
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME-neo4j}/${NEO4J_PASSWORD-password}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_db_tx__log_rotation_retention__policy=false
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
        interval: 15s
        timeout: 30s
        retries: 10
    networks:
      - net

  database-seeding:
    user: "${UID}:${GID}"
    image: neo4j/neo4j-admin:${NEO4J_VERSION-5.21.2}-enterprise
    volumes:
      - $PWD/data:/data
      - $PWD/backups:/backups
      - $PWD/seed-databases.sh:/seed-databases.sh
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_ADDRESS=neo4j://database
      - NEO4J_USERNAME=${NEO4J_USERNAME-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD-password}
    command: /seed-databases.sh
    depends_on:
      database:
        condition: service_healthy
    networks:
      - net

networks:
  net:   

include:
  - docker-compose-sozinianer.yml
 