services:

  sozinianer-loader:
    extends:
      file: template.yml
      service: loader
    volumes:
      - $PWD/embedding_model:/embedding_model
    environment: &sozinianer_env
      NEO4J_DATABASE: sozinianer
      PREPARATION_QUERY: match (t:Text{type:'abstract'}) set t:Abstract
      LABEL: Abstract
      PROPERTY_IDENTIFIER: guid
      PROPERTY_TEXT: text
      PROPERTY_EMBEDDING: embedding
      PROMPT_CONTEXT: den Sozinianischen Briefwechseln
      RETRIEVAL_QUERY: |
        MATCH (node)<-[:HAS_TEXT]-(m:Metadata)
        WITH node, score, 'https://sozinianer.mni.thm.de/view/' + m.guid AS url
        MATCH (node)-[:HAS_ANNOTATION]->(a:Spo)
        WHERE not a.teiType in ['p']
        WITH node, score, collect(a) as annotations, url
        RETURN reduce(str='###Personen und Orte:\n', x in annotations | str + coalesce(x.type, x.teiType) + ': ' + x.text + '\n' ) + 
            '\n###Text: ' + node.text AS text,
            score,
            { source: url } AS metadata
        ORDER BY score ASC
    ports:
      - 8502:8080

  sozinianer-bot:
    extends:
      file: template.yml
      service: bot
    volumes:
      - $PWD/embedding_model:/embedding_model
    environment:
      <<: *sozinianer_env
    ports:
      - 8501:8080

  sozinianer-api:
    extends:
      file: template.yml
      service: api
    environment:
      <<: *sozinianer_env
    volumes:
      - $PWD/embedding_model:/embedding_model
    ports:
      - 8504:8080

  # front-end:
  #   build:
  #     context: .
  #     dockerfile: front-end.Dockerfile
  #   x-develop:
  #     watch:
  #       - action: sync
  #         path: ./front-end
  #         target: /app
  #         ignore:
  #           - ./front-end/node_modules/
  #       - action: rebuild
  #         path: ./front-end/package.json
  #   depends_on:
  #     api:
  #       condition: service_healthy
  #   networks:
  #     - net
  #   ports:
  #     - 8505:8505

